name: Deploy to Heroku Hosting on merge
"on":
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Install git
        run: |
          sudo apt-get -y install git
          which git

      - name: Install heroku-cli
        run: |
          curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
          which heroku

      - name: Remote to heroku repository
        run: heroku git:remote -a ${{ secrets.HEROKU_REPOSITORY }}

      - name: Deploy to heroku
        run: git push heroku main
